Feat: kvstore
liftedinit/talib pull request #274
Opened 2023-09-06 01:09 UTC by jgryffindor

Added KVStore neighborhood and endpoints support to events parser. 

## Description
**Client:**
- Added kvstore.put and kvstore.transfer to client methods and layouts.
- Added alert to transactions page for errors when network selector is on the wrong network context.
- Adding new charts for Network IPv4 bandwidth and packet counts.

**Server:**
- Added put/transfer to server event attributes parser.
- Added update put endpoint to prometheus query endpoint to make it easier to update queries. 

Fixes # (issue)

## Testing
- Tested locally against a clone of prod database. 

## Breaking Changes (if applicable)

None

## Screenshots (if applicable)
![image](https://github.com/liftedinit/talib/assets/3028410/125178c1-1514-40db-ab1f-8587aa54a96f)
![image](https://github.com/liftedinit/talib/assets/3028410/43db6ac8-2eb1-449d-a737-c3c627874fae)

## Checklist:

- [ ] I have read and followed the CONTRIBUTING guidelines for this project.
- [ ] I have added or updated tests and they pass.
- [ ] I have added or updated documentation and it is accurate.
- [ ] I have noted any breaking changes in this module or downstream modules.

2023-09-06 14:38 UTC, fmorency requested changes
The `mnvqws6lhkm` `To` is not a MANY address. Something is wrong.

It would also be nice to display the `Key` and `Value` fields as well, in hex. Be careful as the `Value` field can be very big, e.g., 500Kb.

I glanced at the packet stuff but didn't do an in-depth review.

In the future, it would be nice if you could do 1 PR per feature as opposed to 1 PR with multiple unrelated changes.

2023-09-06 14:38 UTC, fmorency commented on server/src/utils/protocol/attributes/kvstore/kvstore.put.ts
> +      owner: (parseAddress(payload.get(2)) || sender).toString(),
I don't think that's right, see https://github.com/many-protocol/specification/blob/main/attributes/network/cddl/7_kvstore_commands.cddl

2023-09-06 14:38 UTC, fmorency commented on server/src/utils/protocol/attributes/kvstore/kvstore.transfer.ts
> +      new_owner: parseAddress(payload.get(2)).toString(),
I don't think that's right, see https://github.com/many-protocol/specification/blob/main/attributes/network/cddl/7_kvstore_commands.cddl

2023-09-12 21:03 UTC, jgryffindor commented on server/src/utils/protocol/attributes/kvstore/kvstore.transfer.ts
>        key: payload.get(1).toString(),
See update!

2023-09-12 21:03 UTC, jgryffindor commented on server/src/utils/protocol/attributes/kvstore/kvstore.transfer.ts
> +      key: parseBuffer(payload.get(0)).toString(),
See update!

2023-09-12 21:03 UTC, jgryffindor commented on server/src/utils/protocol/attributes/kvstore/kvstore.put.ts
> +      value: parseBuffer(payload.get(1)).toString(),
See update!

2023-09-12 21:04 UTC, jgryffindor commented on server/src/utils/protocol/analyzer.ts
> +  10000: parseAddressTag,
Yahtzee!

2023-09-13 14:52 UTC, fmorency approved these changes

2023-09-13 17:48 UTC, merged